[package]
name = "croftsoft"
version = "0.2.0"
authors = ["David Wallace Croft <david@croftsoft.com>"]
description = "Re-export of com-croftsoft-* crates"
edition = "2021"
homepage = "http://www.croftsoft.com/"
license = "MIT"
# publish = false
readme = "README.md"
repository = "https://github.com/david-wallace-croft/croftsoft"

[dependencies]
com-croftsoft-core = "0.2.0"
